# Generated by Django 4.0.6 on 2023-08-29 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
